//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasserWerkVerwaltung.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Wir bitten Sie, Ihren Wasserzähler innerhalb des Ablesezeitraumes (25.11.07 bis 
09.12.2007) abzulesen und den Zählerstand im unteren Feld einzutragen. 
Vergleichen Sie bitte die anderen Daten auf ihre Richtigkeit. 
Sollten Sie Hilfe beim Ablesen benötigen, stehen wir Ihnen gerne zur Verfügung. 
Tel: 07434/44398 oder 0676/620 32 38 Ing. Waltraud Weinberger-Hairas
Mit freundlichen Grüßen, Ihr Wasserwerk Weinberger
")]
        public string TextZaeholerstandformular {
            get {
                return ((string)(this["TextZaeholerstandformular"]));
            }
            set {
                this["TextZaeholerstandformular"] = value;
            }
        }
    }
}
